server:
  port: 8000

spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://apiuser:apipassword@postgres:5432/ordersdb}
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 10m
      max-acquire-time: 5s
      max-create-connection-time: 5s
      validation-query: SELECT 1
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    io.r2dbc: ERROR
    io.netty: ERROR
