micronaut:
  server:
    port: 8000
    netty:
      # threads not set → Netty defaults to 2 × available processors
      max-content-length: 1048576

datasources:
  default:
    url: ${DATASOURCES_DEFAULT_URL:jdbc:postgresql://db:5432/ordersdb}
    username: ${DATASOURCES_DEFAULT_USERNAME:apiuser}
    password: ${DATASOURCES_DEFAULT_PASSWORD:apipassword}
    maximum-pool-size: 120
    minimum-idle: 10
    driver-class-name: org.postgresql.Driver

jackson:
  property-naming-strategy: SNAKE_CASE

logger:
  root:
    level: ERROR
