default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 16 } %>
  timeout: 5000
  prepared_statements: false
  checkout_timeout: 5

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://apiuser:apipassword@localhost:5432/ordersdb" } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://apiuser:apipassword@localhost:5432/ordersdb" } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://apiuser:apipassword@localhost:5432/ordersdb" } %>
