default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 90 } %>
  timeout: 5000
  prepared_statements: true
  variables:
    statement_timeout: 10000

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://apiuser:apipassword@localhost:5432/ordersdb" } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://apiuser:apipassword@localhost:5432/ordersdb" } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://apiuser:apipassword@localhost:5432/ordersdb" } %>
